'use strict'
var cLanguages = ['en', 'ja'];
var cLang = {
    // common
    cmn_sp        : [' '        , ''           ],
    cmn_enable    : ['enable'   , '有効'       ],
    cmn_none      : ['none'     , 'なし'       ],
    cmn_type      : ['type'     , '種類'       ],
    cmn_mode      : ['mode'     , 'モード'     ],
    cmn_width     : ['width'    , '幅'         ],
    cmn_height    : ['height'   , '高さ'       ],
    cmn_train     : ['train'    , '編成'       ],
    cmn_default   : ['default'  , '既定'       ],
    cmn_sec       : ['sec'      , '秒'         ],
    cmn_position  : ['position' , '位置'       ],
    cmn_offset    : ['offset'   , '補正'       ],
    cmn_angle     : ['angle'    , '角度'       ],
    cmn_direction : ['direction', '方向'       ],
    cmn_slope     : ['slope'    , '勾配'       ],
    cmn_cant      : ['cant'     , 'カント'     ],
    cmn_random    : ['random'   , 'ランダム'   ],
    cmn_left      : ['left'     , '左'         ],
    cmn_right     : ['right'    , '右'         ],
    cmn_apply     : ['apply'    , '適用'       ],
    cmn_cancel    : ['cancel'   , '中止'       ],
    cmn_delete    : ['delete'   , '削除'       ],
    cmn_turnout   : ['turnout'  , '分岐'       ],
    cmn_station   : ['station'  , '停車'       ],
    cmn_settings  : ['settings' , '設定'       ],
    cmn_true      : ['true'     , '有効'       ],
    cmn_false     : ['false'    , '無効'       ],
    cmn_name      : ['name'     , '名称'       ],
    cmn_comment   : ['comment'  , 'コメント'   ],
    cmn_label     : ['label'    , '表記'       ],
    cmn_value     : ['value'    , '値'         ],
    cmn_values    : ['values'   , '値'         ],
    cmn_id        : ['ID'       , 'ID'         ],
    cmn_ids       : ['ID(s)'    , 'ID (複数可)'],
    cmn_color     : ['color'    , '色'         ],
    cmn_colors    : ['colors'   , '色'         ],
    cmn_remove    : ['remove'   , '撤去'       ],
    cmn_switch    : ['switch'   , 'スイッチ'   ],
    cmn_switches  : ['switches' , 'スイッチ'   ],
    cmn_any       : ['any'      , '任意'       ],
    cmn_scale     : ['scale'    , 'スケール'   ],
    cmn_rotate    : ['rotate'   , '回転'       ],
    cmn_trans     : ['trans'    , '移動'       ],
    cmn_condition : ['condition', '条件'       ],
    cmn_parts     : ['parts'    , '部品'       ],
    cmn_model     : ['model'    , 'モデル'     ],
    cmn_checked   : ['checked'  , '選択'       ],
    cmn_depended  : ['depended' , '依存'       ],
    cmn_author    : ['author'   , '作者'       ],
    cmn_shape     : ['shape'    , '形状'       ],
    cmn_smokes    : ['smokes'   , '発煙'       ],
    // ui ctrl
    ui_copy          : ['copy'         , '複製'    ],
    ui_paste         : ['paste'        , '貼付'    ],
    ui_shorten_range : ['shorten range', '範囲縮小'],
    ui_extend_range  : ['extend range' , '範囲拡大'],
    // ui struct
    ui_select_all   : ['select all'     , '全選択'  ],
    ui_add_element  : ['add an element' , '要素追加'],
    ui_del_elements : ['delete elements', '要素削除'],
    ui_move_down    : ['move down'      , '下移動'  ],
    ui_move_up      : ['move up'        , '上移動'  ],
    // menu
    menu_undo         : ['Undo'        , '取消'      ],
    menu_redo         : ['Redo'        , '復帰'      ],
    menu_file         : ['File'        , 'ﾌｧｲﾙ'      ],
    menu_save         : ['Save'        , '保存'      ],
    menu_watch        : ['Watch Mode'  , '鑑賞モード'],
    menu_build_rail   : ['Build Track' , '線路設置'  ],
    menu_edit_rail    : ['Edit Track'  , '線路編集'  ],
    menu_schedule     : ['Schedule   ' , '運行設定'  ],
    menu_edit_model   : ['Part Model'  , '部品モデル'],
    menu_train_model  : ['Train Model' , '車輌モデル'],
    menu_train_list   : ['Train List'  , '編成管理'  ],
    menu_struct_model : ['Struct Model', '施設モデル'],
    menu_struct_list  : ['Struct List' , '施設管理'  ],
    menu_field_editor : ['Edit Field'  , '地形編集'  ],
    // headers
    head_log          : ['LOG'         , 'ログ'      ],
    head_info         : ['INFO'        , '情報'      ],
    head_menu         : ['MENU'        , '操作'      ],
    head_file         : ['FILE'        , 'ファイル'  ],
    head_watch        : ['WATCH MODE'  , '鑑賞モード'],
    head_rail         : ['TRACK'       , '線路'      ],
    head_schedule     : ['SCHEDULE'    , '運行設定'  ],
    head_edit_model   : ['PART MODEL'  , '部品モデル'],
    head_train_model  : ['TRAIN MODEL' , '車輌モデル'],
    head_train_list   : ['TRAIN LIST'  , '編成管理'  ],
    head_struct_model : ['STRUCT MODEL', '施設モデル'],
    head_struct_list  : ['STRUCT LIST' , '施設管理'  ],
    head_field_editor : ['EDIT FIELD'  , '地形編集'  ],
    // debug
    debug_draw     : ['Debug\nDraw', 'デバッグ\n描画'],
    debug_set_lang : ['Language'   , '言語切替'      ],
    // watch
    watch_pause        : ['pause'          , '一時停止'  ],
    watch_sim_speed    : ['sim speed'      , '再生速度'  ],
    watch_fix_camera   : ['fix camera'     , '視点固定'  ],
    watch_rot_focus    : ['rotate focus'   , '回転連動'  ],
    watch_zoom_focus   : ['zoom focus'     , 'ズーム連動'],
    watch_multi_focus  : ['multi focus'    , '複数注目'  ],
    watch_inspect_mode : ['inspection mode', '検査モード'],
    watch_photo_mode   : ['photograph mode', '撮影モード'],
    // camera guide
    cam_guide_open    : ['camera control guide'     , 'カメラ操作ガイド'  ],
    cam_guide_close   : ['close control guide'      , '操作ガイドを閉じる'],
    cam_guide_rotate  : ['rotate camera'            , 'カメラ回転'        ],
    cam_guide_pan     : ['move vertically'          , '垂直移動'          ],
    cam_guide_slide   : ['move horizontally'        , '水平移動'          ],
    cam_guide_forward : ['move forward/backward'    , '前後移動'          ],
    cam_guide_fov     : ['adjust field of view'     , '視野角調整'        ],
    cam_guide_offcent : ['adjust perspective center', '透視中心調整'      ],
    cam_key_rotate    : ['drag'             , 'ドラッグ'         ],
    cam_key_pan       : ['shift + alt(opt)' , 'shift + alt(opt)' ],
    cam_key_slide     : ['alt(opt)'         , 'alt(opt)'         ],
    cam_key_forward   : ['shift / wheel'    , 'shift / ホイール' ],
    cam_key_fov       : ['shift + ctrl(cmd)', 'shift + ctrl(cmd)'],
    cam_key_offcent   : ['ctrl(cmd)'        , 'ctrl(cmd)'        ],
    // rail properties
    track_field_setting : ['field setting', '地表設定'  ],
    track_field_height  : ['field height' , '地表高度'  ],
    track_elevated      : ['height'       , '高さ'      ],
    track_curve_factor  : ['curve factor' , 'カーブ係数'],
    track_rail          : ['rail'         , 'レール'    ],
    track_tie           : ['tie'          , '枕木'      ],
    track_girder        : ['girder'       , '橋桁'      ],
    track_pier          : ['pier'         , '橋脚'      ],
    track_interval      : ['interval'     , '間隔'      ],
    track_part          : ['part'         , 'パーツ'    ],
    // rail types
    rail_narrow   : ['1,067mm narrow gauge'  , '1,067mm 狭軌'     ],
    rail_standard : ['1,435mm standard gauge', '1,435mm 標準軌'   ],
    rail_safege   : ['SAFEGE monorail'       , 'サフェージュ式モノレール'],
    rail_alweg    : ['ALWEG monorail'        , 'アルヴェーグ式モノレール'],
    // tie types
    tie_ballast : ['ballast', 'バラスト'],
    tie_slab    : ['slab'   , 'スラブ'  ],
    // girder types
    girder_girder : ['girder', '橋桁'    ],
    girder_tunnel : ['tunnel', 'トンネル'],
    // pier types
    pier_center : ['center'    , '中央'],
    pier_both   : ['both side' , '両側'],
    pier_left   : ['left side' , '左側'],
    pier_right  : ['right side', '右側'],
    // rail parts types
    part_platform : ['platform', 'ホーム'],
    part_wall     : ['wall'    , '壁'    ],
    part_floor    : ['floor'   , '床'    ],
    // rail part metrics
    part_dimensions : ['dimensions', '寸法'],
    // schedule
    travel_dir : ['travel direction', '進行方向'],
    // turnout
    switch_dir_main : ['main'     , '主'      ],
    switch_dir_sub  : ['sub'      , '副'      ],
    switch_dir_alt  : ['alternate', '交互'    ],
    switch_dir_rnd  : ['random'   , 'ランダム'],
    // station
    station_signal_name : ['signal ID  ', '閉塞 ID'],
    station_dir_any     : ['all'        , '両方'   ],
    station_stop        : ['stop'       , '停車'   ],
    station_turnaround  : ['turnaround' , '折返し' ],
    station_time        : ['time'       , '時間'   ],
    station_model       : ['model'      , '形式'   ],
    // model
    model_draw_pass      : ['draw pass'     , '描画パス'      ],
    model_pass_field     : ['field'         , '地形'          ],
    model_pass_tunnel    : ['tunnel'        , 'トンネル'      ],
    model_pass_default   : ['default'       , 'デフォルト'    ],
    model_default_color  : ['default color' , 'デフォルト色'  ],
    model_override_color : ['override color', '上書き色'      ],
    model_default_value  : ['default value' , 'デフォルト値'  ],
    model_preview_value  : ['preview value' , 'プレビュー値'  ],
    model_compare        : ['compare'       , '比較'          ],
    model_value_ids      : ['value ID(s)'   , '値 ID (複数可)'],
    model_primitives     : ['primitives'    , '基本形状'      ],
    model_painters       : ['painters'      , '塗装'          ],
    model_face           : ['face'          , '面'            ],
    model_split          : ['split'         , '分割'          ],
    model_taper          : ['taper'         , 'テーパ'        ],
    model_base_color     : ['base color'    , '下地色'        ],
    model_solid          : ['solid'         , '充填'          ],
    model_slicers        : ['slicers'       , '切削'          ],
    model_reshapable     : ['reshapable'    , '再成形可能'    ],
    model_bound          : ['bound'         , '境界'          ],
    model_bounds         : ['bounds'        , '境界'          ],
    model_alt_color      : ['alt color'     , '色変更'        ],
    model_accept_focus   : ['accept focus'  , '注目可能'      ],
    // smoke
    smoke_life       : ['lifetime'   , '寿命'        ],
    smoke_scale_fin  : ['final scale', '最終スケール'],
    smoke_speed_damp : ['speed damp' , '速度減衰'    ],
    smoke_emit_ratio : ['emit ratio' , '放出率'      ],
    smoke_turbulence : ['turbulence' , '乱流'        ],
    // primitive types
    primitive_plane    : ['plane'   , '平面'  ],
    primitive_prism    : ['prism'   , '三角柱'],
    primitive_cube     : ['cube'    , '直方体'],
    primitive_cylinder : ['cylinder', '円柱'  ],
    primitive_sphere   : ['sphere'  , '球'    ],
    // face types
    face_front : ['front', '表面'],
    face_back  : ['back' , '裏面'],
    face_both  : ['both' , '両面'],
    // slicer types
    slicer_erase_lt   : ['erase <'  , '消去 <'  ],
    slicer_erase_gt   : ['erase >'  , '消去 >'  ],
    slicer_reshape_lt : ['reshape <', '再成形 <'],
    slicer_reshape_gt : ['reshape >', '再成形 >'],
    // painter types
    painter_mask_lt  : ['mask <'     , 'マスク <'],
    painter_mask_gt  : ['mask >'     , 'マスク >'],
    painter_paint_lt : ['paint <'    , '塗装 <'  ],
    painter_paint_gt : ['paint >'    , '塗装 >'  ],
    painter_alt_lt   : ['alt color <', '色変更 <'],
    painter_alt_gt   : ['alt color >', '色変更 >'],
    // painter shapes
    painter_shape_plane  : ['plane' , '平面'],
    painter_shape_circle : ['circle', '円'  ],
    painter_shape_sphere : ['sphere', '球'  ],
    // train
    train_length       : ['length'      , '全長'      ],
    train_railtype     : ['rail type'   , 'レール種別'],
    train_fixed_to     : ['fixed to'    , '固定先'    ],
    train_fixed_to_pos : ['fixed to pos', '固定先位置'],
    train_rod_length   : ['rod length'  , 'ロッド長'  ],
    train_go           : ['go'          , '運行'      ],
    train_back         : ['back'        , '後退'      ],
    train_speed        : ['speed'       , '速度'      ],
    train_accel        : ['acceleration', '加速度'    ],
    train_decel        : ['deceleration', '減速度'    ],
    train_model        : ['model'       , '形式'      ],
    train_flip         : ['flip'        , '反転'      ],
    train_cars         : ['cars'        , '車輌'      ],
    // train part type
    train_part_wheel     : ['wheel'       , '車輪'          ],
    train_part_bogie     : ['bogie'       , '台車'          ],
    train_part_body      : ['body'        , '車体'          ],
    train_part_rod_tri   : ['triangle rod', '三角ロッド'    ],
    train_part_rod_slide : ['slider rod'  , 'スライダロッド'],
    // struct
    struct_model         : ['model'           , '形式'      ],
    struct_field_setting : ['field setting'   , '地形設定'  ],
    struct_fs_none       : ['none'            , 'なし'      ],
    struct_fs_height     : ['position'        , '位置'      ],
    struct_fs_normal     : ['position & angle', '位置・角度'],
    struct_put_struct    : ['put struct'      , '施設配置'  ],
    // field
    field_layer        : ['layer'        , 'レイヤ'      ],
    field_draw         : ['draw'         , '描画'        ],
    field_draw_all     : ['all layers'   , '全レイヤ'    ],
    field_draw_current : ['current layer', '現在のレイヤ'],
    field_draw_others  : ['other layers' , '他のレイヤ'  ],
    field_mode_write   : ['write'        , '書込'        ],
    field_mode_erase   : ['erase'        , '消去'        ],
    field_mode_pick    : ['pick'         , '選択'        ],
    field_update_rail  : ['update track' , '線路更新'    ],
    field_grass  : ['grass' , '草'],
    field_desert : ['desert', '砂'],
    field_rock   : ['rock'  , '岩'],
    field_snow   : ['snow'  , '雪'],
    field_water  : ['water' , '水'],
    // actions
    act_build_track       : ['track built'         , '線路設置'        ],
    act_create_sw_point   : ['turnout created'     , '分岐作成'        ],
    act_ctrl_point        : ['control point'       , '制御点'          ],
    act_split_rail        : ['spilt track'         , '線路分割'        ],
    act_move_rail         : ['move point'          , '制御点移動'      ],
    act_delete_rail       : ['delete track'        , '線路削除'        ],
    act_set_rail_type     : ['set curve factor'    , 'カーブ係数指定'  ],
    act_toggle_rail       : ['toggle rail'         , 'レール切替'      ],
    act_set_rail_type     : ['set rail type'       , 'レール種類指定'  ],
    act_toggle_tie        : ['toggle tie'          , '枕木切替'        ],
    act_set_tie_type      : ['set tie type'        , '枕木種類指定'    ],
    act_toggle_girder     : ['toggle girder'       , '橋桁切替'        ],
    act_set_girder_type   : ['set girder type'     , '橋桁種類指定'    ],
    act_toggle_pier       : ['toggle pier'         , '橋脚切替'        ],
    act_set_pier_type     : ['set pier type'       , '橋脚種類指定'    ],
    act_set_pier_interval : ['set pier interval'   , '橋脚間隔指定'    ],
    act_set_pier_offset   : ['set pier position'   , '橋脚位置指定'    ],
    act_set_left_part     : ['set left part'       , '左パーツ指定'    ],
    act_set_right_part    : ['set right part'      , '右パーツ指定'    ],
    act_set_point_z       : ['set point Z'         , '制御点 Z 指定'   ],
    act_set_point_height  : ['set point height'    , '制御点高架指定'  ],
    act_set_point_dir     : ['set point dir'       , '制御点方向指定'  ],
    act_set_point_slope   : ['set point slope'     , '制御点勾配指定'  ],
    act_set_point_cant    : ['set point cant'      , '制御点カント指定'],
    act_set_sw_schedule   : ['set turnout schedule', '分岐運行設定'    ],
    act_set_signal_name   : ['set signal name'     , '閉塞名指定'      ],
    act_set_stn_schedule  : ['set station schecule', '停車運行設定'    ],
    act_create_field      : ['create field'        , '地形作成'        ],
    act_delete_field      : ['delete field'        , '地形削除'        ],
    // file
    file_undo : ['Undo', '元に戻す'],
    file_redo : ['Redo', 'やり直し'],
    file_new_scene : ['new scene', '新規シーン'],
    file_keep_model_data : ['keep model data', 'モデルデータ保持'],
    file_load_scene : ['load scene or model data', 'シーン・モデルデータ読込'],
    file_save_scene : ['save scene', 'シーン保存'],
    file_save_for_embedding : ['embed in RailSimWeb.html', 'RailSimWeb.html に埋め込む'],
    file_confirm_clear_scene : ['The scene is going to be cleared.', 'シーンは消去されます。'],
    file_export_data : ['export data', 'データ出力'],
    file_export_part_model : ['selected part models', '選択した部品モデル'],
    file_export_train_model : ['selected train models with depended part models',
                               '選択した車輌モデルおよび依存部品モデル'],
    file_export_struct_model : ['selected struct models with depended part models',
                                '選択した施設モデルおよび依存部品モデル'],
    file_export_train_form : ['selected train formations', '選択した列車編成'],
    file_download : ['download', 'ダウンロード'],
    file_layout_name : ['layout name', 'レイアウト名'],
    file_fov : ['field of view', '視野角'],
    file_reset_camera : ['reset camera', 'カメラリセット'],
    // descriptions
    desc_delete_last_ctrl_point : ['delete the last control point', '最終制御点削除'],
    desc_delete_selected_rail : ['delete selected track', '選択した線路を削除'],
    desc_select_rail_end : ['select track or control-point', '線路または制御点を選択'],
    desc_select_rail_switch : ['select track or turnout', '線路または分岐を選択'],
    desc_replaced_invalid_id : ['Replaced invalid ID', '不正な ID を置き換えました'],
    desc_valid_letters : ['Valid letters', '有効な文字'],
    desc_comma_separated : ['Multiple items can be specified separated by commas.',
                            'カンマ区切りで複数項目を指定できます。'],
    desc_cannot_paste : [
        'Cannot paste! Value type mismatch.', '型が異なるため貼り付けできません。'],
    desc_touch_device_mode : [
        'Enabled touch device mode.', 'タッチ操作モードが有効です。'],
    desc_save_data : ['Save data', 'データ保存'],
    desc_load_data : ['Load data', 'データ読込'],
    desc_import_data : ['Import data', 'データ入力'],
    desc_train_set : ['Train set', '編成設置'],
    desc_train_removed : ['Train removed', '編成撤去'],
    desc_remove_train : ['remove train from scene', 'シーンから編成を撤去'],
    desc_drop_file : ['drop a file here', 'ここにファイルをドロップ'],
    desc_invalid_data : ['Cannot load: invalid data', '読み込み失敗: 不正なデータ'],
    desc_embed_failed : ['Cannot embed: invalid file', '埋め込み失敗: 不正なファイル'],
    // errors
    error_tag : ['[ERROR] ', '[エラー] '],
    error_file_type : ['invalid file type', '不正なファイルタイプ'],
    error_file_version : ['unsupported version', 'サポート外のバージョン'],
    error_file_no_export_data : ['no data to export', '出力データなし'],
    error_not_deletable : ['not deletable', '削除不可'],
    error_used_by : ['used by', '使用中'],
    // warnings
    warn_tag : ['[WARNING] ', '[警告] '],
    warn_already_exist : ['data already exists', 'データが既に存在します'],
};
